### ISSUE TITLE
Can't load AMD 64-bit .dll on a IA 32-bit platform

### ISSUE THREAD

**Issue by thebitstick** [the96/WinnerMatcher#4]
こんにちは、私は米国人なので日本語がだめなったらごめんなさい。
私が、このエラがあります：

```
PS D:\downloads\PTLogger_b1.1> java.exe -jar .\PTLogger.jar
Exception in thread "JavaFX Application Thread" Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:383)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        ... 5 more
java.lang.UnsatisfiedLinkError: D:\downloads\PTLogger_b1.1\opencv_java341.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at PuyoPuyoTetrisAutoCounter.Main.<clinit>(Main.java:11)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplicationWithArgs$155(LauncherImpl.java:352)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)
PS D:\downloads\PTLogger_b1.1>
```

私が64-bitウインドウズと64-bit Javaがあります。
このプロジェクトがかっこいいなので、試してしたいと思います。

**Comment by the96** [comment]
@thebitstick 
こんにちは。苦手ですが一応英語も…。間違ってたらごめんなさい。
Hello.I'm not good at writing English. I'm sorry if my sentences are incorrect.

ご連絡有難うございます。
Thank you for sending issue.
エラー内容を見る限り、恐らく32bitのJavaで動作しているようです。
I think about your environment is running 32-bit java.
恐らく32bitのJavaにパスが通っていると思うので、パスを64bitのJavaに変更して、64bitのJavaでPT-Loggerを実行してみてください。
If you installed 64-bit java, I suppose your "Path"(System environment variable on Windows) is 32-bit java. Please remove 32-bit java from "Path" and add 64-bit java to "Path", then run this program on 64-bit java.

**Comment by thebitstick** [comment]
The issue I had with my installation of Java is that I never had 64-bit Java, only 32-bit.
私がJavaをインストールしたときに問題となったのは64-bitじゃなくて、32-bit Javaを使用してました。

I searched on the Java site for a 64-bit version and I changed my environment variable to go to the new 64-bit installation, and now PTLogger works just fine.
私はJavaサイトで64-bit版を検索し、新しい 64-bitインストールに移行するために私のシステム環境変数を変更しました。そして今はPTLoggerはうまく動作します。

I think you should compile a 32-bit version of opencv because it seems by default, 32-bit Java is installed when you go to download Java.
私はthe96さんがopencvの32ビット版をコンパイルすべきだと思います。なぜなら、デフォルトではJavaのダウンロードに行くときに32ビットのJavaがインストールされているからです。

ありがとうございました。
